#include "auth.hpp"
#include "models/user.hpp"
#include "models/session.hpp"
#include "submodules/PicaSHA2/picosha2.h"
#include <ctime>
#include <random>

using namespace std;

/*this function is generated by AI
    so I heavely commented it because
    in the time I integrated this
    I didn't have any knowledge in encryption */
std::string AuthManager::generateSalt(int length)
{
    static const char chars[] =
        "abcdefghijklmnopqrstuvwxyz"
        "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
        "0123456789";

    std::string salt;

    /*random_device gets some seed from the hardware
        something like a mouse movement or cpu timing
        as far as I understand
        the mt19937 is Mersenne Twister, a fast pseudorandom number generator.
        the idea is to use slow but true random once to seed  fast but pseudorandom
        generator
         */

    std::mt19937 rng(std::random_device{}());

    /*mt19937` produces raw numbers across a huge range.
     `uniform_int_distribution` maps those numbers into
      your desired range.*/
    std::uniform_int_distribution<> dist(0, sizeof(chars) - 2);

    /*calling the distribution with the engine
    generates one random number in range `[0, 61]`.*/
    for (int i = 0; i < length; i++)
        salt += chars[dist(rng)];

    return salt;
}
bool AuthManager::signup(const std::string &username, const std::string &password, const std::string &email)
{
    User_t new_user{};
    if (username.empty())
    {
        std::cerr << "empty user name\n";
        return false;
    }
    if (this->store.userExists(username))
    {
        std::cerr << "signup: username '" << username << "' already taken\n";
        return false;
    }

    new_user.username = username;

    if (password.empty())
    {
        std::cerr << "signup: empty password\n";
        return false;
    }
    if (email.empty())
    {
        std::cerr << "signup: empty email\n";
        return false;
    }
    new_user.email = email;
    new_user.created_at = time(nullptr);

    new_user.allow_anonymous = false;
    new_user.salt = generateSalt();
    string password_salt_conc = password + new_user.salt;
    std::vector<unsigned char> hash(picosha2::k_digest_size);
    picosha2::hash256(password_salt_conc.begin(), password_salt_conc.end(), hash.begin(), hash.end());
    new_user.password_hash = picosha2::bytes_to_hex_string(hash.begin(), hash.end());

    return this->store.saveUser_t(new_user);
}

std::optional<std::string> AuthManager::login(const std::string &username, const std::string &password)
{
    if (username.empty())
    {
        std::cerr << "empty user name\n";
        return nullopt;
    }
    if (password.empty())
    {
        std::cerr << "empty password\n";
        return nullopt;
    }

    optional<User_t> loaded_user = store.loadUser_t(username);
    if (loaded_user == nullopt)
    {
        std::cerr << "login: user '" << username << "' not found\n";
        return nullopt;
    }
    User_t user = loaded_user.value();
    std::vector<unsigned char> hash(picosha2::k_digest_size);
    string password_salt_conc = password + user.salt;

    picosha2::hash256(password_salt_conc.begin(), password_salt_conc.end(), hash.begin(), hash.end());
    string password_hash = picosha2::bytes_to_hex_string(hash.begin(), hash.end());

    if (password_hash != user.password_hash)
    {
        std::cerr << "login: incorrect password\n";
        return std::nullopt;
    }
    string token = generateSalt(32);
    bool check_session = this->store.saveSession(token, username);
    if (check_session)
    {
        cout << "Welcome: " << user.username << "\n";
        return token;
    }
    else
    {
        std::cerr << "login: couldn't save session\n";
        return nullopt;
    }
}

std::optional<std::string> AuthManager::validateSession(const std::string &token)
{
    if (token.empty())
    {
        cerr << "Auth:Empty Token\n";
        return nullopt;
    }
    optional<Session_t> opt_session = this->store.loadSession(token);
    if (opt_session == nullopt)
    {
        cerr << "invalid token\n";
        return nullopt;
    }

    if (time(nullptr) > opt_session->expires_at)
    {
        cerr << "session expired\n";
        this->store.deleteSession(token);
        return nullopt;
    }
    return opt_session->username;
}

bool AuthManager::logout(const std::string &token)
{
    if(token.empty())
    {
        cerr<<"invalid token\n";
        return false;
    }

    /*one implementation I did is to check
     the validity of the session before deleting
     but that is wrong because if the
     session is expired you can't logout the user which doesn't make
     any sense
    */
    return this->store.deleteSession(token);


}
